web:
  image: node/class:2
  expose:
    - "3000"
  ports:
    - "3000:3000"
  links:
    - mysql
  working_dir: /usr/src/app/
  volumes:
    - .:/usr/src/app/
  environment:
    - MYSQL_ROOT_PASSWORD=password
  command: npm run dock
mysql:
  image: mysql/class:2
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - server/config/:/schema/
  command: sh -c "mysqld && mysql -uroot -ppassword < schema.sql"
